# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2edccf641e82be6e949fbd7b6cb872696bf7d9d3bbe9ecfef50685fff1487b8537a9727e008b91e2598d2bfd49f777890af28c7d9ac8a49f1dcfe5db2c82a3ff

test:
  secret_key_base: ab586ca7ca63ec50cf3bb58d4332d72916781a018bce1986bfe1fb7ed70e656a237d03c37f5f9c73dd54faecfc3bbe946e21ba62178e9d47f82348fbe38fb498

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
